#ifndef VM_EXCEPTION_H
#define VM_EXCEPTION_H

typedef enum ExceptionCode{
	VM_OK,
	VM_INIT_FAIL,
	VM_INIT_SEG_FAIL,
	VM_ACCESS_VIOLATION,
	VM_ILLEGAL_INSTRUCTION,
	VM_INTEGER_DIVIDE_BY_ZERO,
	VM_FLOAT_DIVIDE_BY_ZERO,
	VM_INTEGER_OVERFLOW,
	VM_INTEGER_UNDERFLOW
	VM_STACK_OVERFLOW,
	VM_BUFFER_OVERFLOW
} ExceptionCode;

void raise_exception(ExceptionCode);

#endif //VM_EXCEPTION_H